---
title: "Big Tech Stock Prices"
description: "Analysis of Big Tech stock price data from TidyTuesday"
author: William Albrecht
date: September 29, 2026
format:
  html:
    code-fold: true
execute:
  warning: false
  message: false
---

This dataset contains daily stock prices and trading volume for 14 large tech companies from 2010 to 2023. The line plot below represents the adjusted closing prices for Apple, Microsoft, Nvidia, and Amazon, household tech names with large market capitalizations (the stock prices for these four companies were recorded on 12/29/2022 at the latest). Adjusted closing price is the closing price adjusted for stock splits and dividends issued, so that stock prices can be accurately compared across the observed time frame.

```{r}
library(tidyverse)

big_tech_stock_prices <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2023/2023-02-07/big_tech_stock_prices.csv')

big_tech_stock_prices |>
    filter(stock_symbol == "AAPL" | stock_symbol == "MSFT" | stock_symbol == "NVDA" | stock_symbol == "AMZN") |>
    ggplot(aes(x = date, y = adj_close, color = stock_symbol)) + 
    geom_line(linewidth = 0.4) +
    labs(x = "Date", y = "Adjusted close price (USD)", color = "Ticker", title = "Adjusted closing price, 2010 to 2022")

```

Apple, Microsoft, Nvidia, and Amazon grew rapidly from 2010 to 2021, but fell sharply after their peaks in late 2021 to early 2022. Nvidia and Amazon lost more than half of their value, while Microsoft and Amazon lost a little less than a third of their value. 

Data source: [TidyTuesday, February 7, 2023](https://github.com/rfordatascience/tidytuesday/blob/main/data/2023/2023-02-07/readme.md).

Original data: Evan Gower compiled the data in 2023. The Big Tech Stock Prices data set comes from Yahoo Finance and was obtained through [Kaggle](https://www.kaggle.com/datasets/evangower/big-tech-stock-prices).